version: '3.8'
services:
  redis:
    image: redis:7
    container_name: user-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    container_name: user-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"
  product-postgres:
    image: postgres:17
    container_name: product-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"