version: '3.8'
services:
  redis:
    image: redis:7
    container_name: marketplace-redis
    ports:
      - "6379:6379"
  postgres:
    image: postgres:17
    container_name: marketplace-postgres
    environment:
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: javak
      POSTGRES_DB: marketplace_db
    ports:
      - "5432:5432"